import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { cn } from "@/lib/utils";
import Category from "@/components/Home/Category";
import CartProvider from "@/Provider/CartProvider";
import { Toaster } from "@/components/ui/toaster";
import SessionProviderWrapper from "@/Provider/SessionProviderWrapper";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "e commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-[#121212]")}>
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <CartProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow container mx-auto px-4 md:px-10">
              <SessionProviderWrapper>
                {children}
              </SessionProviderWrapper>
            </main>
            <Toaster />
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
